__default__:
    cpus-per-task: 1
    partition: agap_normal
    job-name: SC.{rule}
    output: Logs_VariantsCallingWorkflow/{rule}.%j.out.txt
    error: Logs_VariantsCallingWorkflow/{rule}.%j.err.txt
    
HaplotypeCaller:
    output: Logs_VariantsCallingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_VariantsCallingWorkflow/{rule}.{wildcards.base}.%j.err.txt

GenomicsDBImport:
    cpus-per-task: "{threads}" 

