channels:
  - conda-forge
  - bioconda

dependencies:
  - bwa-mem2 = 2.2.1
  - bwa = 0.7.17
  - bowtie2 = 2.4.5
  - minimap2 = 2.24
  - samtools = 1.14
  - picard = 2.26.10
  - multiqc = 1.11
  - crossmap = 0.6.3
  - bedtools = 2.30.0
