channels:
  - conda-forge
  - bioconda

dependencies:
  - _libgcc_mutex = 0.1
  - _openmp_mutex = 4.5
  - _r-mutex = 1.0.1
  - alsa-lib = 1.2.3.2
  - bedtools = 2.30.0
  - binutils_impl_linux-64 = 2.39
  - binutils_linux-64 = 2.39
  - bowtie2 = 2.4.5
  - brotli = 1.1.0
  - brotli-bin = 1.1.0
  - brotli-python = 1.1.0
  - bwa = 0.7.17
  - bwa-mem2 = 2.2.1
  - bwidget = 1.9.14
  - bx-python = 0.10.0
  - bzip2 = 1.0.8
  - c-ares = 1.26.0
  - ca-certificates = 2023.11.17
  - cairo = 1.16.0
  - certifi = 2023.11.17
  - charset-normalizer = 3.3.2
  - click = 8.1.7
  - coloredlogs = 15.0.1
  - colormath = 3.0.0
  - contourpy = 1.2.0
  - crossmap = 0.6.3
  - curl = 7.86.0
  - cycler = 0.12.1
  - cython = 3.0.8
  - expat = 2.5.0
  - font-ttf-dejavu-sans-mono = 2.37
  - font-ttf-inconsolata = 3.000
  - font-ttf-source-code-pro = 2.038
  - font-ttf-ubuntu = 0.83
  - fontconfig = 2.14.2
  - fonts-conda-ecosystem = 1
  - fonts-conda-forge = 1
  - fonttools = 4.47.2
  - freetype = 2.12.1
  - fribidi = 1.0.10
  - future = 0.18.3
  - gcc_impl_linux-64 = 9.5.0
  - gcc_linux-64 = 9.5.0
  - gettext = 0.21.1
  - gfortran_impl_linux-64 = 9.5.0
  - gfortran_linux-64 = 9.5.0
  - giflib = 5.2.1
  - graphite2 = 1.3.13
  - gsl = 2.6
  - gxx_impl_linux-64 = 9.5.0
  - gxx_linux-64 = 9.5.0
  - harfbuzz = 2.9.1
  - htslib = 1.15.1
  - humanfriendly = 10.0
  - icu = 68.2
  - idna = 3.6
  - importlib-metadata = 7.0.1
  - jinja2 = 3.1.3
  - jpeg = 9e
  - k8 = 0.2.5
  - kernel-headers_linux-64 = 2.6.32
  - keyutils = 1.6.1
  - kiwisolver = 1.4.5
  - krb5 = 1.19.3
  - lcms2 = 2.12
  - ld_impl_linux-64 = 2.39
  - lerc = 3.0
  - libblas = 3.9.0
  - libbrotlicommon = 1.1.0
  - libbrotlidec = 1.1.0
  - libbrotlienc = 1.1.0
  - libcblas = 3.9.0
  - libcurl = 7.86.0
  - libdeflate = 1.10
  - libedit = 3.1.20191231
  - libev = 4.33
  - libexpat = 2.5.0
  - libffi = 3.4.2
  - libgcc-devel_linux-64 = 9.5.0
  - libgcc-ng = 13.2.0
  - libgfortran-ng = 13.2.0
  - libgfortran5 = 13.2.0
  - libglib = 2.78.3
  - libgomp = 13.2.0
  - libiconv = 1.17
  - liblapack = 3.9.0
  - libnghttp2 = 1.51.0
  - libnsl = 2.0.1
  - libopenblas = 0.3.26
  - libpng = 1.6.42
  - libsanitizer = 9.5.0
  - libssh2 = 1.10.0
  - libstdcxx-devel_linux-64 = 9.5.0
  - libstdcxx-ng = 13.2.0
  - libtiff = 4.3.0
  - libuuid = 2.38.1
  - libwebp-base = 1.3.2
  - libxcb = 1.15
  - libxcrypt = 4.4.36
  - libxml2 = 2.9.12
  - libzlib = 1.2.13
  - lzstring = 1.0.4
  - make = 4.3
  - markdown = 3.5.2
  - markdown-it-py = 3.0.0
  - markupsafe = 2.1.4
  - matplotlib-base = 3.8.2
  - mdurl = 0.1.2
  - minimap2 = 2.24
  - multiqc = 1.11
  - munkres = 1.1.4
  - mysql-connector-c = 6.1.11
  - ncurses = 6.2
  - networkx = 3.2.1
  - numpy = 1.26.3
  - olefile = 0.47
  - openjdk = 11.0.9.1
  - openjpeg = 2.5.0
  - openssl = 1.1.1w
  - packaging = 23.2
  - pango = 1.48.10
  - pcre = 8.45
  - pcre2 = 10.42
  - perl = 5.32.1
  - picard = 2.26.10
  - pillow = 8.4.0
  - pip = 23.3.2
  - pixman = 0.43.2
  - pthread-stubs = 0.4
  - pybigwig = 0.3.18
  - pygments = 2.17.2
  - pyparsing = 3.1.1
  - pysam = 0.19.1
  - pysocks = 1.7.1
  - python = 3.10.2
  - python-dateutil = 2.8.2
  - python_abi = 3.10
  - pyyaml = 6.0.1
  - r-base = 3.6.3
  - readline = 8.1
  - requests = 2.31.0
  - rich = 13.7.0
  - samtools = 1.14
  - sed = 4.8
  - setuptools = 69.0.3
  - simplejson = 3.19.2
  - six = 1.16.0
  - spectra = 0.0.11
  - sqlite = 3.37.0
  - sysroot_linux-64 = 2.12
  - tbb = 2021.7.0
  - tk = 8.6.13
  - tktable = 2.10
  - typing_extensions = 4.9.0
  - tzdata = 2023d
  - ucsc-wigtobigwig = 447
  - unicodedata2 = 15.1.0
  - urllib3 = 2.2.0
  - wheel = 0.42.0
  - xorg-fixesproto = 5.0
  - xorg-inputproto = 2.3.2
  - xorg-kbproto = 1.0.7
  - xorg-libice = 1.1.1
  - xorg-libsm = 1.2.4
  - xorg-libx11 = 1.8.7
  - xorg-libxau = 1.0.11
  - xorg-libxdmcp = 1.1.3
  - xorg-libxext = 1.3.4
  - xorg-libxfixes = 5.0.3
  - xorg-libxi = 1.7.10
  - xorg-libxrender = 0.9.11
  - xorg-libxtst = 1.2.3
  - xorg-recordproto = 1.14.2
  - xorg-renderproto = 0.11.1
  - xorg-xextproto = 7.3.0
  - xorg-xproto = 7.0.31
  - xz = 5.2.6
  - yaml = 0.2.5
  - zipp = 3.17.0
  - zlib = 1.2.13
  - zstd = 1.5.5
