__default__:
    cpus-per-task: 1
    partition: agap_normal
    job-name: DC.{rule}
    output: Logs_DataCleaningWorkflow/{rule}.%j.out.txt
    error: Logs_DataCleaningWorkflow/{rule}.%j.err.txt

Trimming_DemultFastqs:
    output: Logs_DataCleaningWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_DataCleaningWorkflow/{rule}.{wildcards.base}.%j.err.txt
