### GENERAL VARIABLES ###

PAIRED_END: TRUE


### INPUT FILES ###

# Complete this field if the sequencing is in Single_End AND the raw fastq files is multiplexed, if not leave blank: ""
# File extension format: .fastq.gz 
FASTQ: ""

# Complete these two fields if the sequencing is in Paired_End AND the raw fastq files are multiplexed, if not leave blank: ""
# File extension format: _R1.fastq.gz and _R2.fastq.gz
FASTQ_R1: ""
FASTQ_R2: ""

# Complete this field if the raw fastq files are demultiplexed (sequencing Single_end or paired_end), if not leave blank: ""
# File extension format: PairedEnd > sampleX.R1.fastq.gz and sampleX.R2.fastq.gz / SingleEnd > sampleX.fastq.gz 
DEMULT_DIR: "DEMULT"

# Mandatory files:
# Complete this field if the raw fastq files are multiplexed (sequencing Single_end or paired_end), if not leave blank: ""
BARCODE_FILE: ""
# Complete this field in all cases
ADAPT_FILE: "CONFIG/adapter_file_MEL.txt"


### DEMULTIPLEXING PARAMETERS ###

# Complete these two fields if the raw fastq files is multiplexed, if not leave blank: ""
DEMULT_CPUS_PER_TASK: 0
DEMULT_SUBSTITUTIONS: ""


### TRIMMING PARAMETERS ###
TRIMMING_CPUS_PER_TASK: 1
TRIMMING_QUAL: 30
TRIMMING_MIN_LENGTH: 36
