channels:
  - conda-forge
  - bioconda

dependencies:
  - _libgcc_mutex = 0.1
  - _openmp_mutex = 4.5
  - bcftools = 1.15.1
  - brotli-python = 1.1.0
  - bzip2 = 1.0.8
  - c-ares = 1.26.0
  - ca-certificates = 2023.11.17
  - certifi = 2023.11.17
  - charset-normalizer = 3.3.2
  - click = 8.1.7
  - coloredlogs = 15.0.1
  - colormath = 3.0.0
  - cycler = 0.12.1
  - dbus = 1.13.6
  - egglib = 3.1.0
  - expat = 2.5.0
  - fontconfig = 2.14.2
  - freetype = 2.12.1
  - future = 0.18.3
  - gettext = 0.21.1
  - glib = 2.66.3
  - gsl = 2.7
  - gst-plugins-base = 1.14.5
  - gstreamer = 1.14.5
  - htslib = 1.17
  - humanfriendly = 10.0
  - icu = 64.2
  - idna = 3.6
  - importlib-metadata = 7.0.1
  - jinja2 = 3.1.3
  - jpeg = 9e
  - keyutils = 1.6.1
  - kiwisolver = 1.4.5
  - krb5 = 1.20.1
  - ld_impl_linux-64 = 2.40
  - libblas = 3.9.0
  - libcblas = 3.9.0
  - libclang = 9.0.1
  - libcurl = 7.87.0
  - libdeflate = 1.19
  - libedit = 3.1.20191231
  - libev = 4.33
  - libexpat = 2.5.0
  - libffi = 3.2.1
  - libgcc-ng = 13.2.0
  - libgfortran-ng = 13.2.0
  - libgfortran5 = 13.2.0
  - libglib = 2.66.3
  - libgomp = 13.2.0
  - libiconv = 1.17
  - liblapack = 3.9.0
  - libllvm9 = 9.0.1
  - libnghttp2 = 1.51.0
  - libopenblas = 0.3.25
  - libpng = 1.6.39
  - libsqlite = 3.44.2
  - libssh2 = 1.10.0
  - libstdcxx-ng = 13.2.0
  - libuuid = 2.38.1
  - libxcb = 1.16
  - libxcrypt = 4.4.36
  - libxkbcommon = 0.10.0
  - libxml2 = 2.9.10
  - libzlib = 1.2.13
  - lzstring = 1.0.4
  - markdown = 3.5.2
  - markdown-it-py = 3.0.0
  - markupsafe = 2.1.4
  - matplotlib = 3.2.1
  - matplotlib-base = 3.2.1
  - mdurl = 0.1.2
  - multiqc = 1.11
  - ncurses = 6.4
  - networkx = 3.1
  - nspr = 4.35
  - nss = 3.97
  - numpy = 1.23.1
  - openssl = 1.1.1w
  - packaging = 23.2
  - pandas = 1.3.5
  - patsy = 0.5.6
  - pcre = 8.45
  - perl = 5.32.1
  - pip = 23.3.2
  - platformdirs = 4.2.0
  - pooch = 1.8.0
  - pthread-stubs = 0.4
  - pygments = 2.17.2
  - pyparsing = 3.1.1
  - pyqt = 5.12.3
  - pyqt5-sip = 4.19.18
  - pyqtchart = 5.12
  - pyqtwebengine = 5.12.1
  - pysocks = 1.7.1
  - python = 3.8.6
  - python-dateutil = 2.8.2
  - python_abi = 3.8
  - pytz = 2023.4
  - pyyaml = 6.0.1
  - qt = 5.12.5
  - readline = 8.2
  - requests = 2.31.0
  - rich = 13.7.0
  - scipy = 1.10.1
  - seaborn = 0.12.2
  - seaborn-base = 0.12.2
  - setuptools = 59.8.0
  - simplejson = 3.19.2
  - six = 1.16.0
  - spectra = 0.0.11
  - sqlite = 3.44.2
  - statsmodels = 0.14.1
  - tk = 8.6.13
  - tornado = 6.3.3
  - typing_extensions = 4.9.0
  - urllib3 = 2.2.0
  - wheel = 0.42.0
  - xorg-libxau = 1.0.11
  - xorg-libxdmcp = 1.1.3
  - xz = 5.2.6
  - yaml = 0.2.5
  - zipp = 3.17.0
  - zlib = 1.2.13
