__default__:
    pe: smp 1
    q: long.q
    h_vmem: 2G
    N: RM.{rule}
    o: Logs_ReadMappingWorkflow/{rule}.$JOB_ID.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.$JOB_ID.err.txt

Mapping_PairedEndFastqs:
    pe: smp {threads}
    h_vmem: 5G
    o: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

Mapping_SingleEndFastqs:
    pe: smp {threads}
    h_vmem: 5G
    o: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

MarkDuplicates_Bams:
    o: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Index_Bams:
    o: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Stats_Bams:
    o: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

Extract_PairedEndReads:
    o: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

Remapping_PairedEndExtractedFastqs:
    pe: smp {threads}
    h_vmem: 5G
    o: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

Extract_SingleEndReads:
    o: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

Remapping_SingleEndExtractedFastqs:
    pe: smp {threads}
    h_vmem: 5G
    o: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

MarkDuplicates_Subbamss:
    o: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Index_Subbams:
    o: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Stats_Subbams:
    o: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

