### GENERAL VARIABLES ###
OUTPUTS_DIRNAME:  "WORKFLOW_OUTPUTS"
#
#### INPUT FILES ###
#
## Provide the VCF file to be filtered
## the vcf need to be gzipped
VCF_file: "/home/ardissonm/projects/GE2POP/TRITICUM/PARTAGE/CONCAT_GEN_ALR_2_VCF/concat_VR_READS2SNPS_SVEVO_40nident_simul_reads_p40_detect_FIS09_TH101_PAR1_MIN1_b.vcf.gz"

## Mail Johanna
#Pour les sorties de reads2snps j’ai appliqué les filtres habituels :
#- les génotypes avec cov < 5 ou pvalue < 0.95 deviennent NA
#- les SNPs dont le Fis < 0.8 sont supprimés
#- les SNPs non couverts chez au moins 50% des génotypes sont supprimés
#- les SNPs avec des comptes de nucléotides bizarres sont supprimés

## filtering parameters
# https://gatk.broadinstitute.org/hc/en-us/articles/360035531692-VCF-Variant-Call-Format
# http://vcftools.sourceforge.net/man_latest.html
# --minGQ 15.0 (sample level) The Genotype Quality represents the Phred-scaled confidence that the genotype assignment (GT) is correct, derived from the genotype PLs. Specifically, the GQ is the difference between the PL of the second most likely genotype, and the PL of the most likely genotype. 
# --minDP 5 (sample level) The number of filtered reads that support each of the reported alleles. 
# --minQ 30 (site level) The Phred-scaled probability that a REF/ALT polymorphism exists at this site given sequencing data.
# --max-missing 0.5 keep variants that have been successfully genotyped in 50% of individuals

# VCFTOOL options to remove genotypes and site of poorly quality/coverage
#genotype_filter:  "--minGQ 15.0 --minDP 5 --minQ 30 --max-missing 0.5"
# for read2SNP no Q available
genotype_filter:  "--minGQ 15.0 --minDP 5 --max-missing 0.5"
# home made filter to remove individuals having too much missing data after
MAX_percent_NA_per_INDIV: "1"
# BCFTOOL options to keep (include -i) relevant SNPs (-i SNP_FILTER)
#SNP_filter: 'INFO/type=="snp" & INFO/F>0.8 & INFO/A1A1>0 & INFO/A2A2>0'
SNP_filter: "INFO/F>=0.8 & INFO/A1A1>0 & INFO/A2A2>0 & INFO/pcNA<0.5"
