BAM_DIR: ""
OUTPUTS_DIRNAME: ""
REFERENCE: ""


GATK_HAPLOTYPE_CALLER_JAVA_MEM: "-Xmx4g"
GATK_HAPLOTYPE_CALLER_EXTRA_OPTIONS: 

GATK_GENOMICS_DB_IMPORT_JAVA_MEM: "-Xmx30g" 
GATK_GENOMICS_DB_IMPORT_EXTRA_OPTIONS: " --merge-contigs-into-num-partitions 20 --batch-size 50 --reader-threads 20"

GATK_GENOTYPE_GVCFS_JAVA_MEM: 
GATK_GENOTYPE_GVCFS_EXTRA_OPTIONS: 