OUTPUTS_DIRNAME: "WORKFLOW_OUTPUTS"
BAM_DIR: "/home/ardissonm/scratch/TEST_WORKFLOW/SNP_CALLING/MAPPING"

REFERENCE: "/home/ardissonm/scratch/TEST_WORKFLOW/SNP_CALLING_MINI/REFERENCES/Svevo_baits_04_20_2019_0pident_40nident_0length_mini.fasta"


GATK_HAPLOTYPE_CALLER_JAVA_OPTIONS: "-Xmx4g"
GATK_HAPLOTYPE_CALLER_EXTRA_OPTIONS: ""

GATK_GENOMICS_DB_IMPORT_JAVA_OPTIONS: "-Xmx30g" 
GATK_GENOMICS_DB_IMPORT_EXTRA_OPTIONS: " --merge-contigs-into-num-partitions 20 --batch-size 50 --reader-threads 20"

GATK_GENOTYPE_GVCFS_JAVA_OPTIONS: "-Xmx30g"
GATK_GENOTYPE_GVCFS_EXTRA_OPTIONS: "--heterozygosity 0.001"