### GENERAL VARIABLES ###
#OUTPUTS_DIRNAME: "WORKFLOW_OUTPUTS"
PAIRED_END: TRUE
CREATE_SUB_BAMS: TRUE
MAPPING_SUBFOLDER: "MAPPING_TO_SVEVO"


### INPUT FILES ###
# Provide the directory containing the trimmed fastq files to be mapped
TRIM_DIR: ""

# Reference genome
REFERENCE: "/home/jogirodolle/work/REFERENCES/Mini_ref/Svevo_baits_04_20_2019_0pident_40nident_0length_mini.fasta"

# Targeted zones bed file (optionnal)
BED: test.bed


### MAPPING PARAMETERS ###
MAPPER: "bwa-mem2_mem"
REMOVE_DUP: TRUE
SEQUENCING_TECHNOLOGY: "ILLUMINA"
EXTRA_MAPPER_OPTIONS: ""

PICARD_MARKDUPLICATES_OPTIONS: "" #"-MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 1000"

SAMTOOLS_INDEX_OPTIONS: "" #besoin de "-c" quand mapping sur Svevo entier


