### GENERAL VARIABLES ###
#OUTPUTS_DIRNAME: "WORKFLOW_OUTPUTS"
PAIRED_END: TRUE
CREATE_SUB_BAMS: TRUE
MAPPING_SUBFOLDER: "MAPPING_TO_SVEVO"


### INPUT FILES ###
# Provide the directory containing the trimmed fastq files to be mapped
TRIM_DIR: ""

# Reference genome
REFERENCE: "/home/jogirodolle/work/REFERENCES/Mini_ref/Svevo_baits_04_20_2019_0pident_40nident_0length_mini.fasta"

# Targeted zones bed file (optionnal)
BED: test.bed


### MAPPING PARAMETERS ###
MAPPER: "bwa-mem2_mem"
REMOVE_DUP: TRUE
SEQUENCING_TECHNOLOGY: "ILLUMINA"
EXTRA_MAPPER_PARAMS: ""

MARKDUP_PARAMS: "" #"-MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 1000"

INDEX_PARAMS: "" #besoin de "-c" quand mapping sur Svevo entier




#REFERENCE_NAME: "MINI_SVEVO_BAITS"
# Targeted zones group file (optionnal)
#ZONES_GROUPS: zones_groups.tsv

# Samples group file (optionnal)
#SAMPLES_GROUPS: samples_groups.tsv
