### GENERAL VARIABLES ###
PAIRED_END: TRUE
CREATE_SUB_BAMS: TRUE
MAPPING_SUBFOLDER: ""


### INPUT FILES ###
# Provide the directory containing the trimmed fastq files to be mapped
TRIM_DIR: ""

# Reference genome
REFERENCE: ""

# Targeted zones bed file (optionnal)
BED: ""


### MAPPING PARAMETERS ###
MAPPER: ""
REMOVE_DUP: TRUE
SEQUENCING_TECHNOLOGY: ""
EXTRA_MAPPER_OPTIONS: ""
MAPPING_CPUS_PER_TASK: "8"

PICARD_MARKDUPLICATES_OPTIONS: "" #"-MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 1000"

SAMTOOLS_INDEX_OPTIONS: "" #besoin de "-c" quand mapping sur Svevo entier

