__default__:
    cpus-per-task: 1
    partition: agap_normal
    mem: 5G
    job-name: RM.{rule}
    output: Logs_ReadsMappingWorkflow/{rule}.%j.out.txt
    error: Logs_ReadsMappingWorkflow/{rule}.%j.err.txt

Mapping_PairedEndFastqs:
    cpus-per-task: "{threads}"
    output: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Mapping_SingleEndFastqs:
    cpus-per-task: "{threads}"
    output: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Stats_Bams:
    output: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Extract_Reads:
    output: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt

Stats_Subbams:
    output: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.%j.err.txt


