__default__:
    pe: smp 1
    q: long.q
    h_vmem: 2G
    N: RM.{rule}
    o: Logs_ReadsMappingWorkflow/{rule}.$JOB_ID.out.txt
    e: Logs_ReadsMappingWorkflow/{rule}.$JOB_ID.err.txt

Mapping_PairedEndFastqs:
    pe: smp {threads}
    o: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

Mapping_SingleEndFastqs:
    pe: smp {threads}
    o: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

Stats_Bams:
    o: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

Extract_Reads:
    o: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

Stats_Subbams:
    o: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_ReadsMappingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

