### GENERAL VARIABLES ###
PAIRED_END: TRUE
CREATE_SUB_BAMS: TRUE
MAPPING_SUBFOLDER: ""


### INPUT FILES ###
# Path(s) to the directory or directories containing the trimmed fastq files to be mapped. To provide several directories, separate them with spaces.
    # If left blank, the workflow will assume the fastq files are in WORKFLOWS_OUTPUTS/DATA_CLEANING/DEMULT_TRIM, which is the path to our DATA_CLEANING workflow output files. 
TRIM_DIRS: "DEMULT_TRIM"

# Path to the reference file in fasta format (must end with .fa, .fas or .fasta).
REFERENCE: "../REFERENCE/Reference.fasta"

# Path to the bed file listing targeted zones. Optionnal: can be left blank ("").
BED: "../REFERENCE/Reference_targeted_zones.bed"
BED_MIN_MEAN_COV: ""
BED_MAX_DIST: ""
BED_MIN_LENGTH: ""


### MAPPING PARAMETERS ###
MAPPER: "bwa_mem"
REMOVE_DUP: TRUE
SEQUENCING_TECHNOLOGY: "ILLUMINA"
EXTRA_MAPPER_OPTIONS: "-t 4"
MAPPING_CPUS_PER_TASK: 8

PICARD_MARKDUPLICATES_OPTIONS: "-MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 1000"
PICARD_MARKDUPLICATES_JAVA_OPTIONS: ""

SAMTOOLS_INDEX_OPTIONS: "" #use "-c" if mapping to a really big reference genome
