### GENERAL VARIABLES ###
PAIRED_END: TRUE
CREATE_SUB_BAMS: TRUE
MAPPING_SUBFOLDER: ""


### INPUT FILES ###
# Provide the directory containing the trimmed fastq files to be mapped
TRIM_DIRS: "DEMULT_TRIM"

# Reference genome
REFERENCE: "../REFERENCE/Reference.fasta"

# Targeted zones bed file (optionnal)
BED: "../REFERENCE/Reference_targeted_zones.bed"


### MAPPING PARAMETERS ###
MAPPER: "bwa_mem"
REMOVE_DUP: TRUE
SEQUENCING_TECHNOLOGY: "ILLUMINA"
EXTRA_MAPPER_OPTIONS: "-t 4"
MAPPING_CPUS_PER_TASK: 8

PICARD_MARKDUPLICATES_OPTIONS: "-MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 1000"
PICARD_MARKDUPLICATES_JAVA_OPTIONS: ""

SAMTOOLS_INDEX_OPTIONS: "" #use "-c" if mapping to a really big reference genome
