channels:
  - conda-forge
  - bioconda

dependencies:
  - _libgcc_mutex = 0.1
  - _openmp_mutex = 4.5
  - alsa-lib = 1.2.3.2
  - bcftools = 1.15.1
  - brotli-python = 1.1.0
  - bzip2 = 1.0.8
  - c-ares = 1.26.0
  - ca-certificates = 2023.11.17
  - cairo = 1.16.0
  - certifi = 2023.11.17
  - charset-normalizer = 3.3.2
  - cycler = 0.12.1
  - dbus = 1.13.6
  - expat = 2.5.0
  - fontconfig = 2.14.2
  - freetype = 2.12.1
  - gatk4 = 4.2.5.0
  - gettext = 0.21.1
  - giflib = 5.2.1
  - glib = 2.66.3
  - graphite2 = 1.3.13
  - gsl = 2.7
  - gst-plugins-base = 1.14.5
  - gstreamer = 1.14.5
  - harfbuzz = 2.4.0
  - htslib = 1.17
  - icu = 64.2
  - idna = 3.6
  - jpeg = 9e
  - keyutils = 1.6.1
  - kiwisolver = 1.3.0
  - krb5 = 1.20.1
  - lcms2 = 2.12
  - ld_impl_linux-64 = 2.40
  - libblas = 3.9.0
  - libcblas = 3.9.0
  - libclang = 9.0.1
  - libcurl = 7.87.0
  - libdeflate = 1.19
  - libedit = 3.1.20191231
  - libev = 4.33
  - libexpat = 2.5.0
  - libffi = 3.2.1
  - libgcc-ng = 13.2.0
  - libgfortran-ng = 13.2.0
  - libgfortran5 = 13.2.0
  - libglib = 2.66.3
  - libgomp = 13.2.0
  - libiconv = 1.17
  - liblapack = 3.9.0
  - libllvm9 = 9.0.1
  - libnghttp2 = 1.51.0
  - libopenblas = 0.3.25
  - libpng = 1.6.42
  - libsqlite = 3.44.2
  - libssh2 = 1.10.0
  - libstdcxx-ng = 13.2.0
  - libtiff = 4.2.0
  - libuuid = 2.38.1
  - libwebp-base = 1.3.2
  - libxcb = 1.16
  - libxcrypt = 4.4.36
  - libxkbcommon = 0.10.0
  - libxml2 = 2.9.10
  - libzlib = 1.2.13
  - matplotlib = 3.2.1
  - matplotlib-base = 3.2.1
  - ncurses = 6.2
  - nspr = 4.35
  - nss = 3.97
  - numpy = 1.23.1
  - openjdk = 11.0.8
  - openssl = 1.1.1w
  - packaging = 23.2
  - pandas = 1.3.5
  - patsy = 0.5.6
  - pcre = 8.45
  - perl = 5.32.1
  - pip = 23.3.2
  - pixman = 0.38.0
  - platformdirs = 4.2.0
  - pooch = 1.8.0
  - pthread-stubs = 0.4
  - pyparsing = 3.1.1
  - pyqt = 5.12.3
  - pyqt5-sip = 4.19.18
  - pyqtchart = 5.12
  - pyqtwebengine = 5.12.1
  - pysocks = 1.7.1
  - python = 3.8.6
  - python-dateutil = 2.8.2
  - python_abi = 3.8
  - pytz = 2023.4
  - qt = 5.12.5
  - readline = 8.1
  - requests = 2.31.0
  - samtools = 1.14
  - scipy = 1.10.1
  - seaborn = 0.12.2
  - seaborn-base = 0.12.2
  - setuptools = 59.8.0
  - six = 1.16.0
  - sqlite = 3.37.0
  - statsmodels = 0.14.1
  - tk = 8.6.13
  - tornado = 6.3.3
  - typing_extensions = 4.9.0
  - urllib3 = 2.2.0
  - wheel = 0.42.0
  - xorg-fixesproto = 5.0
  - xorg-inputproto = 2.3.2
  - xorg-kbproto = 1.0.7
  - xorg-libice = 1.1.1
  - xorg-libsm = 1.2.4
  - xorg-libx11 = 1.7.2
  - xorg-libxau = 1.0.11
  - xorg-libxdmcp = 1.1.3
  - xorg-libxext = 1.3.4
  - xorg-libxfixes = 5.0.3
  - xorg-libxi = 1.7.10
  - xorg-libxrender = 0.9.10
  - xorg-libxtst = 1.2.3
  - xorg-recordproto = 1.14.2
  - xorg-renderproto = 0.11.1
  - xorg-xextproto = 7.3.0
  - xorg-xproto = 7.0.31
  - xz = 5.2.6
  - zlib = 1.2.13
  - zstd = 1.5.5
