### GENERAL VARIABLES ###

PAIRED_END: TRUE

MAPPING_SUBFOLDER: ""


### INPUT FILES ###
# Path(s) to the directory or directories containing the trimmed fastq files to be mapped. To provide several directories, separate them with spaces.
    # If left blank, the workflow will assume the fastq files are in WORKFLOWS_OUTPUTS/DATA_CLEANING/DEMULT_TRIM, which is the path to our DATA_CLEANING workflow output files. 
TRIM_DIRS: "DEMULT_TRIM"

# Path to the reference file in fasta format (must end with .fa, .fas or .fasta).
REFERENCE: "../REFERENCE/Reference.fasta"


### EXTRACTION OF TRAGETED ZONES ###
# To simplify subsequent steps such as VARIANTS_CALLING, it is possible to extract the reads (bams files) corresponding to specifics zones. 
CREATE_SUB_BAMS: TRUE

# Path to the bed file listing targeted zones for extraction. Optionnal: can be left blank ("").
    # this file can be created with zones of your choice or using the mapping on the genomic reference to determine the most covered zones and store in : WORKFLOWS_OUTPUTS/READS_MAPPING/BAMS/name_file.bed
BED: "../REFERENCE/Reference_targeted_zones.bed"
profondeur min
taille gap pour fusionner
taille min

# parameters for bed file creation



### MAPPING PARAMETERS ###
MAPPER: "bwa_mem"
REMOVE_DUP: TRUE
SEQUENCING_TECHNOLOGY: "ILLUMINA"
EXTRA_MAPPER_OPTIONS: "-t 4"
MAPPING_CPUS_PER_TASK: 8

PICARD_MARKDUPLICATES_OPTIONS: "-MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 1000"
PICARD_MARKDUPLICATES_JAVA_OPTIONS: ""

SAMTOOLS_INDEX_OPTIONS: "" #use "-c" if mapping to a really big reference genome
