__default__:
    pe: smp 1
    h_vmem: 2G
    q: short.q
    N: DC.{rule}
    o: Logs_VariantCallingWorkflow/{rule}.$JOB_ID.out.txt
    e: Logs_VariantCallingWorkflow/{rule}.$JOB_ID.err.txt
   
HaplotypeCaller:
    pe: smp {threads}
    q: bigmem.q
    h_vmem: 27G
    o: Logs_VariantCallingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_VariantCallingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

GenomicsDBImport:
    pe: smp {threads}

Plot_GVCFVariablesHistograms:
    h_vmem: 4G

Plot_GVCFDPBoxplot:
    h_vmem: 4G
    
Plot_GVCFVariantsAlongGenome:
    h_vmem: 4G
