### GENERAL VARIABLES ###



#### INPUT FILES ###

## Provide the VCF file to be filtered. The vcf need to be gzipped
VCF_FILE: "/home/ardissonm/scratch/TEST_WORKFLOW/SNP_CALLING/WORKFLOWS_OUTPUTS/SNP_CALLING/GENOTPYE_GVCFS/variants.vcf.gz"

### VCF FILTERING PARAMETERS ###

## Variants filtering by locus with VCFTOOLS options : can be applied either at the genotype level (locus x samples) (e.g. minGQ, minDP) 
#                                                                      or at the locus level (e.g. minQ, max-missing)
# http://vcftools.sourceforge.net/man_latest.html

# --minGQ 15.0 (sample level) The Genotype Quality represents the Phred-scaled confidence that the genotype assignment (GT) is correct, derived from the genotype PLs. Specifically, the GQ is the difference between the PL of the second most likely genotype, and the PL of the most likely genotype. 
# --minDP 5 (sample level) The number of filtered reads that support each of the reported alleles. 
# --minQ 30 (site level) The Phred-scaled probability that a REF/ALT polymorphism exists at this site given sequencing data.
# --max-missing 0.5 keep variants that have been successfully genotyped in 50% of individuals
# READS2SNP (no Q available)
# LOCUS_FILTERS: "--minGQ 15.0 --minDP 6 --max-missing 0.5"

#GATK
VCFTOOLS_LOCUS_FILTERING_OPTIONS: "--minGQ 15.0 --minDP 5 --minQ 30 --max-missing 0.5"

## Variants filtering by samples. Remove samples that have too many locus with missing data (proportion)
MAX_RATIO_NA_PER_SAMPLE: "1"

## Variants filtering by population genetics statistics 
POPGENSTATS_FILTERING_OPTIONS: "INFO/F>=0.8 & INFO/A1A1>0 & INFO/A2A2>0 & INFO/pcNA<0.5"
