cluster: "sbatch --partition {cluster.partition} --job-name {cluster.job-name} --error {cluster.error} --output {cluster.output} --cpus-per-task {cluster.cpus-per-task} --mem {cluster.mem}"
latency-wait: 20
jobs: 1