#### INPUT FILES ###

VCF_FILE: ""
FILTERING_SUBFOLDER: ""

### VCF FILTERING PARAMETERS ###
BCFTOOLS_GENOTYPES_FILTERING_OPTIONS: ""
BCFTOOLS_LOCUS_FILTERING1_OPTIONS: ""
MAX_NA_PER_SAMPLE: ""
BCFTOOLS_LOCUS_FILTERING2_OPTIONS: ""
