# Used for cleaning sample names. Should be strings.
# NB: These are removed in order!
fn_clean_exts:
  - ".gz"
  - ".fastq"
  - ".fq"
  - ".bam"
  - ".sam"
  - ".sra"
  - ".vcf"
  - ".dat"
  - "_tophat"
  - ".pbmarkdup.log"
  - ".log"
  - ".stderr"
  - ".out"
  - ".spp"
  - ".fa"
  - ".fasta"
  - ".png"
  - ".jpg"
  - ".jpeg"
  - ".html"
  - "Log.final"
  - "ReadsPerGene"
  - ".flagstat"
  - "_star_aligned"
  - "_fastqc"
  - ".hicup"
  - ".counts"
  - "_counts"
  - ".txt"
  - ".tsv"
  - ".csv"
  - ".aligned"
  - "Aligned"
  - ".merge"
  - ".deduplicated"
  - ".dedup"
  - ".clean"
  - ".sorted"
  - ".report"
  - "| stdin"
  - ".geneBodyCoverage"
  - ".inner_distance_freq"
  - ".junctionSaturation_plot.r"
  - ".pos.DupRate.xls"
  - ".GC.xls"
  - "_slamdunk"
  - "_bismark"
  - ".conpair"
  - ".concordance"
  - ".contamination"
  - ".BEST.results"
  - "_peaks.xls"
  - ".relatedness"
  - ".cnt"
  - ".aqhist"
  - ".bhist"
  - ".bincov"
  - ".bqhist"
  - ".covhist"
  - ".covstats"
  - ".ehist"
  - ".gchist"
  - ".idhist"
  - ".ihist"
  - ".indelhist"
  - ".lhist"
  - ".mhist"
  - ".qahist"
  - ".qchist"
  - ".qhist"
  - ".rpkm"
  - ".selfSM"
  - ".extendedFrags"
  - "_SummaryStatistics"
  - ".purple.purity"
  - ".purple.qc"
  - ".trim"
  - ".bowtie2"
  - ".mkD"
  - ".highfreq"
  - ".lowfreq"
  - ".consensus"
  - ".snpEff"
  - ".snpeff"
  - ".scaffolds"
  - ".contigs"
  - ".kraken2"
  - ".ccurve"
  - ".hisat2"
  - "_duprate"
  - ".markdup"
  - ".read_distribution"
  - ".junction_annotation"
  - ".infer_experiment"
  - ".biotype"
  - ".ivar"
  - ".mpileup"
  - ".primer_trim"
  - ".mapped"
  - ".vep"
  - "_vep"
  - "ccs"
  - "_NanoStats"
  - ".cutadapt"
  - ".mosdepth"
  - "stats_"
  - "_zones"
  
# These are removed after the above, only if sample names
# start or end with this string. Again, removed in order.
fn_clean_trim:
  - "."
  - ":"
  - "_"
  - "-"
  - ".r"
  - "_val"
  - ".idxstats"
  - "_trimmed"
  - ".trimmed"
  - ".csv"
  - ".yaml"
  - ".yml"
  - ".json"
  - "_mqc"
  - "short_summary_"
  - "_summary"
  - ".summary"
  - ".align"
  - ".h5"
  - "_matrix"
  - ".stats"
  - ".hist"
  - ".phased"