### GENERAL VARIABLES ###
WORKFLOW_DIR: "/home/jogirodolle/save/CAPTURE_PIPELINES_SNAKEMAKE"
WORKDIR: "/home/jogirodolle/work/DATA_TEST/VIR"
OUTPUTS_DIRNAME: "WORKFLOW_OUTPUTS"

### INPUT FILES ###
FASTQ_R1: "/home/jogirodolle/work/DATA_TEST/VIR/RAWDATA/CapBleVirus_S1_L001_R1_001.fastq.gz"
FASTQ_R2: "/home/jogirodolle/work/DATA_TEST/VIR/RAWDATA/CapBleVirus_S1_L001_R2_001.fastq.gz"
TAG_FILE: "/home/jogirodolle/work/DATA_TEST/VIR/CONFIG/tag_file_VIR_Cap001.txt"
ADAPT_FILE: "/home/jogirodolle/work/DATA_TEST/VIR/CONFIG/adapter_file_VIR_Cap001.txt"

### DEMULTIPLEXING PARAMETERS ###
DEMULT_THREADS: 1
DEMULT_SUBSTITUTIONS: 0.1

### TRIMMING PARAMETERS ###
TRIMMING_THREADS: 1
TRIMMING_QUAL: 30
TRIMMING_MIN_LENGTH: 36
