### GENERAL VARIABLES ###
PAIRED_END: TRUE
CREATE_SUB_BAMS: ""
MAPPING_SUBFOLDER: ""


### INPUT FILES ###
# Provide the directory containing the trimmed fastq files to be mapped
TRIM_DIRS: ""

# Reference genome
REFERENCE: ""

# Targeted zones bed file (optionnal)
BED: ""
BED_MIN_MEAN_COV: ""
BED_MIN_DIST: ""
BED_MIN_LENGTH: ""


### MAPPING PARAMETERS ###
MAPPER: ""
SEQUENCING_TECHNOLOGY: ""
EXTRA_MAPPER_OPTIONS: ""

PICARD_MARKDUPLICATES_OPTIONS: "" #"-MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 1000"
PICARD_MARKDUPLICATES_JAVA_OPTIONS: ""

SAMTOOLS_INDEX_OPTIONS: "" #besoin de "-c" quand mapping sur Svevo entier

### BAM FILTERING ###
## After the first mapping
REMOVE_DUP_MARKDUPLICATES: ""
REMOVE_DUP_UMI: ""
UMITOOLS_DEDUP_OPTIONS: ""

# options passed to 'samtools view'
SAMTOOLS_VIEW_FILTERS1: ""

## After the remapping (options passed to 'samtools view'). If CREATE_SUB_BAMS is set to FALSE, leave blank (the command will not be called anyway)
SAMTOOLS_VIEW_FILTERS2: ""